### ISSUE TITLE
More Meta Tags Will Be Better

### ISSUE THREAD

**Issue by robynmaya** [maning83/prj-rev-bwfs-dasmoto#1]
https://github.com/maning83/prj-rev-bwfs-dasmoto/blob/63ebf792b66fb21b26156d9ecc367e8d2b0c0086/Dasmoto/index.html#L3-L7

Try including various types of meta tags on your HTML next time, for example :

```
<meta name="description" content="Dasmoto is great">
<meta name="keywords" content="Dasmoto, paint, ink, canvas">
<meta name="author" content=“John Doe">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

A description will appear on search engine as a brief description of your page, although it may or may not affect your page/site ranking, but it is a good practice still - at least, a compelling description can entice more visitors to come to your site.

A viewport element gives the browser instructions on how to control the page's dimensions and scaling.

The width=device-width part sets the width of the page to follow the screen-width of the device (which will vary depending on the device).

The initial-scale=1.0 part sets the initial zoom level when the page is first loaded by the browser.

[Read more](https://support.google.com/webmasters/answer/79812?hl=en)

**Comment by maning83** [comment]
Thank you, Maya, for the comments and clear explanation.
It is very helpful. I have added the meta tags to my exercise.
I will pay more attention in the future when I building my own websites.
