### ISSUE TITLE
Section Separation

### ISSUE THREAD

**Issue by robynmaya** [maning83/prj-rev-bwfs-dasmoto#2]
https://github.com/maning83/prj-rev-bwfs-dasmoto/blob/63ebf792b66fb21b26156d9ecc367e8d2b0c0086/Dasmoto/index.html#L10-L22

For better readability, you may put a line break after each div, to separate each section from each other. 

You can also use an HTML5 Semantic Element, `<section></section>`, in place of `div`s to encapsulate a group of relevant content. For example `<section></section>` for details on frames, another `<section></section>` for details on brushes, etc.

More about HTML5 Semantic Elements [here](https://www.w3schools.com/html/html5_semantic_elements.asp)

**Comment by maning83** [comment]
Thank you, Maya.
Again, very helpful comments.
Because of your comments, I searched and now learned the differences between section and div.
