### ISSUE TITLE
Class Names

### ISSUE THREAD

**Issue by robynmaya** [maning83/prj-rev-bwfs-dasmoto#3]
https://github.com/maning83/prj-rev-bwfs-dasmoto/blob/63ebf792b66fb21b26156d9ecc367e8d2b0c0086/Dasmoto/index.html#L10

The idea of using a `class` is so that we could reuse the style. But in this case, you want to apply a unique style for each section (and for each `class` you declared, you didn't reuse the `class` either). So the best way to achieve that is by using `id` in place of `class`, and the names can still be the same (`brushes, frames, paint`).

**Comment by maning83** [comment]
Thank you, Maya. You are right.
id is more suitable for this situation.
I have revised the code accordingly.
