### ISSUE TITLE
Don't Use HTML As Your CSS Selector

### ISSUE THREAD

**Issue by robynmaya** [maning83/prj-rev-bwfs-dasmoto#4]
https://github.com/maning83/prj-rev-bwfs-dasmoto/blob/63ebf792b66fb21b26156d9ecc367e8d2b0c0086/Dasmoto/resources/style.css#L1

You should use `* ` element/selector if you want to apply a universal font-family. 

[Read more](https://www.sitepoint.com/css-selectors/)

**Comment by maning83** [comment]
Thank you, Maya.
Good to learn about this the universal selector.
I had the doubt if html would be the right element to use when I was coding.
