### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by robynmaya** [maning83/prj-rev-bwfs-dasmoto#5]
Grade : Satisfactory 

You did a good job overall. You can try experiment with using HTML5 Semantic Elements. I would recommend you to include more Meta Tags for your next projects and to follow best practices when working CSS, especially the selectors. 

Reading material for you: 

1. [CSS Selectors ](https://www.sitepoint.com/css-selectors/)
2. [HTML5 Semantic Elements](https://codepen.io/mi-lee/post/an-overview-of-html5-semantics)

**Comment by maning83** [comment]
Thank you, Maya.
I learned a lot from this exercise and from you.
Appreciate.
